services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
      # args:
      #   NEXT_PUBLIC_WEB_APP_URL: https://address-of-webapp-goes-here.com/

    restart: unless-stopped
    ports:
      - "8001:8000"
